var snowStorm=function(e,c){function g(a,c){isNaN(c)&&(c=0);return Math.random()*a+c}function q(){e.setTimeout(function(){a.start(!0)},20);a.events.remove(j?c:e,"mousemove",q)}function t(){if(!a.excludeMobile||!u)a.freezeOnBlur?a.events.add(j?c:e,"mousemove",q):q();a.events.remove(e,"load",t)}this.autoStart=!0;this.flakesMax=128;this.flakesMaxActive=64;this.animationInterval=33;this.excludeMobile=!0;this.flakeBottom=null;this.followMouse=!0;this.snowColor="#fff";this.snowCharacter="&bull;";this.snowStick=
!0;this.targetElement=null;this.useMeltEffect=!0;this.usePositionFixed=this.useTwinkleEffect=!1;this.freezeOnBlur=!0;this.flakeRightOffset=this.flakeLeftOffset=0;this.flakeHeight=this.flakeWidth=8;this.vMaxX=5;this.vMaxY=4;this.zIndex=0;var a=this,C=this,j=navigator.userAgent.match(/msie/i),D=navigator.userAgent.match(/msie 6/i),E=navigator.appVersion.match(/windows 98/i),u=navigator.userAgent.match(/mobile|opera m(ob|in)/i),F=j&&"BackCompat"===c.compatMode,v=u||F||D,h=null,l=null,k=null,m=null,w=
null,x=null,r=1,n=!1,s;a:{try{c.createElement("div").style.opacity="0.5"}catch(I){s=!1;break a}s=!0}var y=!1,z=c.createDocumentFragment();this.timers=[];this.flakes=[];this.active=this.disabled=!1;this.meltFrameCount=20;this.meltFrames=[];var A=function(a){a=G.call(a);var c=a.length;p?(a[1]="on"+a[1],3<c&&a.pop()):3===c&&a.push(!1);return a},B=function(a,c){var e=a.shift(),f=[H[c]];if(p)e[f](a[0],a[1]);else e[f].apply(e,a)},p=!e.addEventListener&&e.attachEvent,G=Array.prototype.slice,H={add:p?"attachEvent":
"addEventListener",remove:p?"detachEvent":"removeEventListener"};this.events={add:function(){B(A(arguments),"add")},remove:function(){B(A(arguments),"remove")}};this.randomizeWind=function(){var d;d=g(a.vMaxX,0.2);w=1===parseInt(g(2),10)?-1*d:d;x=g(a.vMaxY,0.2);if(this.flakes)for(d=0;d<this.flakes.length;d++)this.flakes[d].active&&this.flakes[d].setVelocities()};this.scrollHandler=function(){var d;m=a.flakeBottom?0:parseInt(e.scrollY||c.documentElement.scrollTop||c.body.scrollTop,10);isNaN(m)&&(m=
0);if(!n&&!a.flakeBottom&&a.flakes)for(d=a.flakes.length;d--;)0===a.flakes[d].active&&a.flakes[d].stick()};this.resizeHandler=function(){e.innerWidth||e.innerHeight?(h=e.innerWidth-16-a.flakeRightOffset,k=a.flakeBottom?a.flakeBottom:e.innerHeight):(h=(c.documentElement.clientWidth||c.body.clientWidth||c.body.scrollWidth)-(!j?8:0)-a.flakeRightOffset,k=a.flakeBottom?a.flakeBottom:c.documentElement.clientHeight||c.body.clientHeight||c.body.scrollHeight);l=parseInt(h/2,10)};this.resizeHandlerAlt=function(){h=
a.targetElement.offsetLeft+a.targetElement.offsetWidth-a.flakeRightOffset;k=a.flakeBottom?a.flakeBottom:a.targetElement.offsetTop+a.targetElement.offsetHeight;l=parseInt(h/2,10)};this.freeze=function(){var d;if(a.disabled)return!1;a.disabled=1;for(d=a.timers.length;d--;)clearInterval(a.timers[d])};this.resume=function(){if(a.disabled)a.disabled=0;else return!1;a.timerInit()};this.toggleSnow=function(){a.flakes.length?(a.active=!a.active,a.active?(a.show(),a.resume()):(a.stop(),a.freeze())):a.start()};
this.stop=function(){var d;this.freeze();for(d=this.flakes.length;d--;)this.flakes[d].o.style.display="none";a.events.remove(e,"scroll",a.scrollHandler);a.events.remove(e,"resize",a.resizeHandler);a.freezeOnBlur&&(j?(a.events.remove(c,"focusout",a.freeze),a.events.remove(c,"focusin",a.resume)):(a.events.remove(e,"blur",a.freeze),a.events.remove(e,"focus",a.resume)))};this.show=function(){var a;for(a=this.flakes.length;a--;)this.flakes[a].o.style.display="block"};this.SnowFlake=function(a,e,j,f){var b=
this;this.type=e;this.x=j||parseInt(g(h-20),10);this.y=!isNaN(f)?f:-g(k)-12;this.vY=this.vX=null;this.vAmpTypes=[1,1.2,1.4,1.6,1.8];this.vAmp=this.vAmpTypes[this.type];this.melting=!1;this.meltFrameCount=a.meltFrameCount;this.meltFrames=a.meltFrames;this.twinkleFrame=this.meltFrame=0;this.active=1;this.fontSize=10+10*(this.type/5);this.o=c.createElement("div");this.o.innerHTML=a.snowCharacter;this.o.style.color=a.snowColor;this.o.style.position=n?"fixed":"absolute";this.o.style.width=a.flakeWidth+
"px";this.o.style.height=a.flakeHeight+"px";this.o.style.fontFamily="arial,verdana";this.o.style.cursor="default";this.o.style.overflow="hidden";this.o.style.fontWeight="normal";this.o.style.zIndex=a.zIndex;z.appendChild(this.o);this.refresh=function(){if(isNaN(b.x)||isNaN(b.y))return!1;b.o.style.left=b.x+"px";b.o.style.top=b.y+"px"};this.stick=function(){v||a.targetElement!==c.documentElement&&a.targetElement!==c.body?b.o.style.top=k+m-a.flakeHeight+"px":a.flakeBottom?b.o.style.top=a.flakeBottom+
"px":(b.o.style.display="none",b.o.style.top="auto",b.o.style.bottom="0px",b.o.style.position="fixed",b.o.style.display="block")};this.vCheck=function(){0<=b.vX&&0.2>b.vX?b.vX=0.2:0>b.vX&&-0.2<b.vX&&(b.vX=-0.2);0<=b.vY&&0.2>b.vY&&(b.vY=0.2)};this.move=function(){var c=b.vX*r;b.x+=c;b.y+=b.vY*b.vAmp;b.x>=h||h-b.x<a.flakeWidth?b.x=0:0>c&&b.x-a.flakeLeftOffset<-a.flakeWidth&&(b.x=h-a.flakeWidth-1);b.refresh();k+m-b.y<a.flakeHeight?(b.active=0,a.snowStick?b.stick():b.recycle()):(a.useMeltEffect&&(b.active&&
3>b.type&&!b.melting&&0.998<Math.random())&&(b.melting=!0,b.melt()),a.useTwinkleEffect&&(b.twinkleFrame?(b.twinkleFrame--,b.o.style.visibility=b.twinkleFrame&&0===b.twinkleFrame%2?"hidden":"visible"):0.9<Math.random()&&(b.twinkleFrame=parseInt(20*Math.random(),10))))};this.animate=function(){b.move()};this.setVelocities=function(){b.vX=w+g(0.12*a.vMaxX,0.1);b.vY=x+g(0.12*a.vMaxY,0.1)};this.setOpacity=function(a,b){if(!s)return!1;a.style.opacity=b};this.melt=function(){!a.useMeltEffect||!b.melting?
b.recycle():b.meltFrame<b.meltFrameCount?(b.setOpacity(b.o,b.meltFrames[b.meltFrame]),b.o.style.fontSize=b.fontSize-b.fontSize*(b.meltFrame/b.meltFrameCount)+"px",b.o.style.lineHeight=a.flakeHeight+2+0.75*a.flakeHeight*(b.meltFrame/b.meltFrameCount)+"px",b.meltFrame++):b.recycle()};this.recycle=function(){b.o.style.display="none";b.o.style.position=n?"fixed":"absolute";b.o.style.bottom="auto";b.setVelocities();b.vCheck();b.meltFrame=0;b.melting=!1;b.setOpacity(b.o,1);b.o.style.padding="0px";b.o.style.margin=
"0px";b.o.style.fontSize=b.fontSize+"px";b.o.style.lineHeight=a.flakeHeight+2+"px";b.o.style.textAlign="center";b.o.style.verticalAlign="baseline";b.x=parseInt(g(h-a.flakeWidth-20),10);b.y=parseInt(-1*g(k),10)-a.flakeHeight;b.refresh();b.o.style.display="block";b.active=1};this.recycle();this.refresh()};this.snow=function(){for(var d=0,c=0,e=0,f=null,f=a.flakes.length;f--;)1===a.flakes[f].active?(a.flakes[f].move(),d++):0===a.flakes[f].active?c++:e++,a.flakes[f].melting&&a.flakes[f].melt();d<a.flakesMaxActive&&
(f=a.flakes[parseInt(g(a.flakes.length),10)],0===f.active&&(f.melting=!0))};this.mouseMove=function(d){if(!a.followMouse)return!0;d=parseInt(d.clientX,10);d<l?r=-2+2*(d/l):(d-=l,r=2*(d/l))};this.createSnow=function(d,c){var e;for(e=0;e<d;e++)if(a.flakes[a.flakes.length]=new a.SnowFlake(a,parseInt(g(6),10)),c||e>a.flakesMaxActive)a.flakes[a.flakes.length-1].active=-1;C.targetElement.appendChild(z)};this.timerInit=function(){a.timers=!E?[setInterval(a.snow,a.animationInterval)]:[setInterval(a.snow,
3*a.animationInterval),setInterval(a.snow,a.animationInterval)]};this.init=function(){var d;for(d=0;d<a.meltFrameCount;d++)a.meltFrames.push(1-d/a.meltFrameCount);a.randomizeWind();a.createSnow(a.flakesMax);a.events.add(e,"resize",a.resizeHandler);a.events.add(e,"scroll",a.scrollHandler);a.freezeOnBlur&&(j?(a.events.add(c,"focusout",a.freeze),a.events.add(c,"focusin",a.resume)):(a.events.add(e,"blur",a.freeze),a.events.add(e,"focus",a.resume)));a.resizeHandler();a.scrollHandler();a.followMouse&&a.events.add(j?
c:e,"mousemove",a.mouseMove);a.animationInterval=Math.max(20,a.animationInterval);a.timerInit()};this.start=function(d){if(y){if(d)return!0}else y=!0;if("string"===typeof a.targetElement&&(d=a.targetElement,a.targetElement=c.getElementById(d),!a.targetElement))throw Error('Snowstorm: Unable to get targetElement "'+d+'"');a.targetElement||(a.targetElement=!j?c.documentElement?c.documentElement:c.body:c.body);a.targetElement!==c.documentElement&&a.targetElement!==c.body&&(a.resizeHandler=a.resizeHandlerAlt);
a.resizeHandler();a.usePositionFixed=a.usePositionFixed&&!v;n=a.usePositionFixed;h&&(k&&!a.disabled)&&(a.init(),a.active=!0)};a.autoStart&&a.events.add(e,"load",t,!1);return this}(window,document);